### ISSUE TITLE
FabLab-Neuch

### ISSUE THREAD

**Issue by LnCarrel** [cwalther/cookie-cutter-sweeper#1]
Hi Christian,

I saw your cookie cutter project and I am very interested in using it.
Does it work? And how ? :)

Thank's

**Comment by cwalther** [comment]
Come to our [Christmas workshop](http://www.fablabwinti.ch/kurse/weihnachtsworkshop-fuer-kinder-und-erwachsene-guetzliausstecher-und-weihnachtsdekoration/) to find out! ;)

If you don’t want to build the program yourself, I recommend you download it from the [releases page](https://github.com/cwalther/cookie-cutter-sweeper/releases). There’s a readme in there that should explain the basics. If it doesn’t, come back and ask.

The easy way to use the program is as an Inkscape extension. The more flexible way is on the command line. Both are contained in the release zip.

**Comment by LnCarrel** [comment]
Thank's you for your answer. I did it in Inkscape !!!!! Your extension is perfect. :)
Have you ever tried to make internal zones? I would love to do that : http://copypastry.net

**Comment by cwalther** [comment]
That looks like a hard thing to automate completely (there’s probably a reason why CopyPastry sell the service, not the software), but with a bit of hand work that should be doable. I have never tried it, but I imagine you could make the outer cutter and the embossing stamp separately with Cookie Cutter Sweeper (with different profiles) and then connect them with some hand-placed bars in a 3D modeling application. Or even model and print them as two separate parts so you can use the embossing stamp to push the cookie out of the cutter.
