### ISSUE TITLE
Popen: 

### ISSUE THREAD

**Issue by raphaelmonnard** [cwalther/cookie-cutter-sweeper#4]
Hello, I tried to export a simple form with the cookie-cutter-sweeper extension, and get:

`Traceback (most recent call last):
  File "export.py", line 60, in <module>
    process = subprocess.Popen([os.path.join(os.getcwd(), bindir, 'sweep'), '--flip-x', os.path.join(os.getcwd(), 'section.png'), os.path.join(tempdir, 'cookie.png'), os.path.expanduser(options.outputfile)], stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied`

I'm on archlinux x64. Could you help me?

**Comment by raphaelmonnard** [comment]
FIX need to `chmod +x linux-x86_64/sweep`

**Comment by cwalther** [comment]
Did you install it from the zipped release? If so, how did you unzip it? When I use `unzip`, it has the correct premissions.

**Comment by cwalther** [comment]
I just re-tested on Linux and get correct permissions both with `unzip` and File Roller, so I believe there is nothing wrong here. If you do find anything, please reopen.
